@id=
@code=

###

GET {{base_url}}/v1/se/locations/search
Authorization: Bearer {{access_token}}

###

GET {{base_url}}/v1/se/locations/{{id}}
Authorization: Bearer {{access_token}}

###

GET {{base_url}}/v1/se/locations/code/{{code}}
Authorization: Bearer {{access_token}}

###

PUT {{base_url}}/v1/se/locations
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "code": "Location1",
  "name": "Location1",
  "address": "Location1",
  "seasonId": "01976221-1cdc-77ec-a691-1fa784c016cc"
}