@id=
@code=

###

GET {{base_url}}/v1/se/regions/search
Authorization: Bearer {{access_token}}

###

GET {{base_url}}/v1/se/regions/{{id}}
Authorization: Bearer {{access_token}}

###

GET {{base_url}}/v1/se/regions/code/{{code}}
Authorization: Bearer {{access_token}}

###

PUT {{base_url}}/v1/se/regions
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "code": "Region1",
  "name": "Region1",
  "seasonId": "01976221-1cdc-77ec-a691-1fa784c016cc"
}