@id=
@code=

###

GET {{base_url}}/v1/se/sports/search
Authorization: Bearer {{access_token}}

###

GET {{base_url}}/v1/se/sports/{{id}}
Authorization: Bearer {{access_token}}

###

GET {{base_url}}/v1/se/sports/code/{{code}}
Authorization: Bearer {{access_token}}

###

PUT {{base_url}}/v1/se/sports
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "code": "",
  "name": "",
  "seasonId": ""
}