@id=
@code=

###

GET {{base_url}}/v1/se/sports/search
Authorization: Bearer {{access_token}}

###

GET {{base_url}}/v1/se/sports/{{id}}
Authorization: Bearer {{access_token}}

###

GET {{base_url}}/v1/se/sports/code/{{code}}
Authorization: Bearer {{access_token}}

###

PUT {{base_url}}/v1/se/sports
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "code": "",
  "name": "",
  "seasonId": ""
}

###

GET {{base_url}}/v1/se/sports/categories/search
Authorization: Bearer {{access_token}}

###

GET {{base_url}}/v1/se/sports/categories/{{id}}
Authorization: Bearer {{access_token}}

###

GET {{base_url}}/v1/se/sports/categories/code/{{code}}
Authorization: Bearer {{access_token}}

###

PUT {{base_url}}/v1/se/sports/categories
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "id": "",
  "code": "",
  "name": "",
  "rule": "",
  "sportId": ""
}
