@id=
@code=

###

GET {{base_url}}/v1/se/units/search
Authorization: Bearer {{access_token}}

###

GET {{base_url}}/v1/se/units/{{id}}
Authorization: Bearer {{access_token}}

###

GET {{base_url}}/v1/se/units/code/{{code}}
Authorization: Bearer {{access_token}}

###

PUT {{base_url}}/v1/se/units
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "code": "Unit1",
  "name": "Unit1",
  "seasonId": "01976221-1cdc-77ec-a691-1fa784c016cc"
}